# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'testingInterface.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog2(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(369, 800)
        Dialog.setMinimumSize(QtCore.QSize(300, 800))
        self.trackModelButton = QtWidgets.QDialogButtonBox(Dialog)
        self.trackModelButton.setGeometry(QtCore.QRect(50, 720, 251, 31))
        self.trackModelButton.setOrientation(QtCore.Qt.Horizontal)
        self.trackModelButton.setStandardButtons(QtWidgets.QDialogButtonBox.Apply|QtWidgets.QDialogButtonBox.Reset)
        self.trackModelButton.setObjectName("trackModelButton")
        self.block = QtWidgets.QPushButton(Dialog)
        self.block.setGeometry(QtCore.QRect(130, 30, 201, 51))
        self.block.setObjectName("block")
        self.blockSpinBox = QtWidgets.QSpinBox(Dialog)
        self.blockSpinBox.setGeometry(QtCore.QRect(20, 30, 71, 51))
        self.blockSpinBox.setObjectName("blockSpinBox")
        self.failureCondition = QtWidgets.QGroupBox(Dialog)
        self.failureCondition.setGeometry(QtCore.QRect(20, 390, 311, 271))
        self.failureCondition.setObjectName("failureCondition")
        self.trackCircFailButton = QtWidgets.QPushButton(self.failureCondition)
        self.trackCircFailButton.setGeometry(QtCore.QRect(60, 110, 201, 51))
        self.trackCircFailButton.setObjectName("trackCircFailButton")
        self.trackCircFailButton_2 = QtWidgets.QPushButton(self.failureCondition)
        self.trackCircFailButton_2.setGeometry(QtCore.QRect(60, 180, 201, 51))
        self.trackCircFailButton_2.setObjectName("trackCircFailButton_2")
        self.powerFailButton = QtWidgets.QPushButton(self.failureCondition)
        self.powerFailButton.setGeometry(QtCore.QRect(60, 30, 201, 51))
        self.powerFailButton.setObjectName("powerFailButton")
        self.swSelectButton = QtWidgets.QPushButton(Dialog)
        self.swSelectButton.setGeometry(QtCore.QRect(130, 100, 201, 51))
        self.swSelectButton.setObjectName("swSelectButton")
        self.swSpinBox = QtWidgets.QSpinBox(Dialog)
        self.swSpinBox.setGeometry(QtCore.QRect(20, 100, 71, 51))
        self.swSpinBox.setObjectName("swSpinBox")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(20, 170, 311, 201))
        self.groupBox.setObjectName("groupBox")
        self.swSendPositionButton = QtWidgets.QPushButton(self.groupBox)
        self.swSendPositionButton.setGeometry(QtCore.QRect(50, 120, 201, 51))
        self.swSendPositionButton.setObjectName("swSendPositionButton")
        self.swSpinBox_2 = QtWidgets.QSpinBox(self.groupBox)
        self.swSpinBox_2.setGeometry(QtCore.QRect(50, 60, 71, 51))
        self.swSpinBox_2.setObjectName("swSpinBox_2")
        self.swPosSpinBox = QtWidgets.QSpinBox(self.groupBox)
        self.swPosSpinBox.setGeometry(QtCore.QRect(180, 60, 71, 51))
        self.swPosSpinBox.setObjectName("swPosSpinBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(40, 30, 91, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(160, 30, 101, 16))
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Dialog)
        self.trackModelButton.accepted.connect(Dialog.accept)
        self.trackModelButton.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.block.setText(_translate("Dialog", "Select Block"))
        self.failureCondition.setTitle(_translate("Dialog", "Failure States:"))
        self.trackCircFailButton.setText(_translate("Dialog", "Send Track Failure"))
        self.trackCircFailButton_2.setText(_translate("Dialog", "Send Broken Rail"))
        self.powerFailButton.setText(_translate("Dialog", "Send Power Failure"))
        self.swSelectButton.setText(_translate("Dialog", "Select Switch"))
        self.groupBox.setTitle(_translate("Dialog", "Change Switch"))
        self.swSendPositionButton.setText(_translate("Dialog", "Send New Switch Position"))
        self.label.setText(_translate("Dialog", "Switch Selector"))
        self.label_2.setText(_translate("Dialog", "Position Selector"))
