# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'trackModel_mainPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


#Imports
from PyQt5    import QtCore, QtGui, QtWidgets, Qt

    
class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1920, 1080)
        Dialog.setMinimumSize(QtCore.QSize(1920, 500))
        #QGraphicsScene
        self.trackLayout = QtWidgets.QGraphicsScene(Dialog)
        self.trackLayout.setObjectName("trackLayout")
        #QGraphicsView
        self.trackLayoutView = QtWidgets.QGraphicsView(Dialog)
        self.trackLayoutView.setGeometry(QtCore.QRect(360, 140, 1251, 781))
        self.trackLayoutView.setObjectName("trackLayoutView")
        #QPushButton
        self.browseFileSelectButton = QtWidgets.QPushButton(Dialog)
        self.browseFileSelectButton.setGeometry(QtCore.QRect(1800, 850, 111, 61))
        self.browseFileSelectButton.setObjectName("browseFileSelectButton")
        #QPushButton
        self.uploadTrackButton = QtWidgets.QPushButton(Dialog)
        self.uploadTrackButton.setGeometry(QtCore.QRect(1620, 850, 171, 61))
        self.uploadTrackButton.setObjectName("uploadTrackButton")
        #QGroupBox
        self.envTemp = QtWidgets.QGroupBox(Dialog)
        self.envTemp.setGeometry(QtCore.QRect(1770, 550, 141, 81))
        self.envTemp.setObjectName("envTemp")
        #QLCDNumber
        self.lcdEnvTemp = QtWidgets.QLCDNumber(self.envTemp)
        self.lcdEnvTemp.setGeometry(QtCore.QRect(23, 30, 81, 31))
        self.lcdEnvTemp.setObjectName("lcdEnvTemp")
        #QGroupBox
        self.grad = QtWidgets.QGroupBox(Dialog)
        self.grad.setGeometry(QtCore.QRect(1620, 630, 141, 71))
        self.grad.setObjectName("grad")
        #QLCDNumber
        self.lcdGrad = QtWidgets.QLCDNumber(self.grad)
        self.lcdGrad.setGeometry(QtCore.QRect(20, 30, 81, 31))
        self.lcdGrad.setObjectName("lcdGrad")
        #QGroupBox
        self.elev = QtWidgets.QGroupBox(Dialog)
        self.elev.setGeometry(QtCore.QRect(1770, 630, 141, 71))
        self.elev.setObjectName("elev")
        #QLCDNumber
        self.lcdElev = QtWidgets.QLCDNumber(self.elev)
        self.lcdElev.setGeometry(QtCore.QRect(20, 30, 81, 31))
        self.lcdElev.setObjectName("lcdElev")
        #QGroupBox
        self.blockSize = QtWidgets.QGroupBox(Dialog)
        self.blockSize.setGeometry(QtCore.QRect(1620, 550, 141, 81))
        self.blockSize.setObjectName("blockSize")
        #QLCDNumber
        self.lcdBlockSize = QtWidgets.QLCDNumber(self.blockSize)
        self.lcdBlockSize.setGeometry(QtCore.QRect(23, 30, 81, 31))
        self.lcdBlockSize.setObjectName("lcdBlockSize")
        #QGroupBox
        self.blockSelectorGroup = QtWidgets.QGroupBox(Dialog)
        self.blockSelectorGroup.setGeometry(QtCore.QRect(1620, 140, 151, 381))
        self.blockSelectorGroup.setObjectName("blockSelectorGroup")
        #QScrollArea
        self.blockSelScrollArea = QtWidgets.QScrollArea(self.blockSelectorGroup)
        self.blockSelScrollArea.setGeometry(QtCore.QRect(10, 30, 121, 331))
        self.blockSelScrollArea.setWidgetResizable(True)
        self.blockSelScrollArea.setObjectName("blockSelScrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 119, 329))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.blockSelScrollArea.setWidget(self.scrollAreaWidgetContents)
        #QGroupBox
        self.switches = QtWidgets.QGroupBox(Dialog)
        self.switches.setGeometry(QtCore.QRect(180, 350, 161, 251))
        self.switches.setObjectName("switches")
        #QScrollArea
        self.swScrollArea = QtWidgets.QScrollArea(self.switches)
        self.swScrollArea.setGeometry(QtCore.QRect(30, 30, 111, 211))
        self.swScrollArea.setWidgetResizable(True)
        self.swScrollArea.setObjectName("swScrollArea")
        self.swScrollAreaWidgetContents = QtWidgets.QWidget()
        self.swScrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 109, 209))
        self.swScrollAreaWidgetContents.setObjectName("swScrollAreaWidgetContents")
        self.swScrollArea.setWidget(self.swScrollAreaWidgetContents)
        #QGroupBox
        self.signals = QtWidgets.QGroupBox(Dialog)
        self.signals.setGeometry(QtCore.QRect(10, 350, 161, 251))
        self.signals.setObjectName("signals")
        #QScrollArea
        self.signScrollArea = QtWidgets.QScrollArea(self.signals)
        self.signScrollArea.setGeometry(QtCore.QRect(20, 30, 111, 211))
        self.signScrollArea.setWidgetResizable(True)
        self.signScrollArea.setObjectName("signScrollArea")
        self.signScrollAreaWidgetContents = QtWidgets.QWidget()
        self.signScrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 109, 209))
        self.signScrollAreaWidgetContents.setObjectName("signScrollAreaWidgetContents")
        self.signScrollArea.setWidget(self.signScrollAreaWidgetContents)
        #QtextBrowser
        self.textBrowser = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser.setGeometry(QtCore.QRect(1625, 810, 281, 31))
        self.textBrowser.setObjectName("textBrowser")
        #QGroupBox
        self.signals_2 = QtWidgets.QGroupBox(Dialog)
        self.signals_2.setGeometry(QtCore.QRect(20, 130, 331, 211))
        self.signals_2.setObjectName("signals_2")
        #QLabel
        self.brokenRailTxt = QtWidgets.QLabel(self.signals_2)
        self.brokenRailTxt.setGeometry(QtCore.QRect(20, 40, 111, 31))
        self.brokenRailTxt.setObjectName("brokenRailTxt")
        #QLabel
        self.trackCircuitTxt = QtWidgets.QLabel(self.signals_2)
        self.trackCircuitTxt.setGeometry(QtCore.QRect(20, 90, 131, 31))
        self.trackCircuitTxt.setObjectName("trackCircuitTxt")
        #QLabel
        self.powerTxt = QtWidgets.QLabel(self.signals_2)
        self.powerTxt.setGeometry(QtCore.QRect(20, 140, 111, 31))
        self.powerTxt.setObjectName("powerTxt")
        #QGroupBox
        self.failureBR = QtWidgets.QGroupBox(Dialog)
        self.failureBR.setGeometry(QtCore.QRect(20, 130, 331, 211))
        self.failureBR.setObjectName("failureBR")        
        #QLCDNumber
        self.lcdBrokenRail = QtWidgets.QLCDNumber(self.failureBR)
        self.lcdBrokenRail.setGeometry(QtCore.QRect(220, 40, 64, 23))
        self.lcdBrokenRail.setObjectName("lcdBrokenRail")
        #QGroupBox
        self.failureTC = QtWidgets.QGroupBox(Dialog)
        self.failureTC.setGeometry(QtCore.QRect(20, 130, 331, 211))
        self.failureTC.setObjectName("failureTC")
        #QLCDNumber
        self.lcdTrackCircuit = QtWidgets.QLCDNumber(self.failureTC)
        self.lcdTrackCircuit.setGeometry(QtCore.QRect(220, 90, 64, 23))
        self.lcdTrackCircuit.setObjectName("lcdTrackCircuit")
        #QGroupBox
        self.failurePower = QtWidgets.QGroupBox(Dialog)
        self.failurePower.setGeometry(QtCore.QRect(20, 130, 331, 211))
        self.failurePower.setObjectName("failurePower")
        #QLCDNumber
        self.lcdPower = QtWidgets.QLCDNumber(self.failurePower)
        self.lcdPower.setGeometry(QtCore.QRect(220, 150, 64, 23))
        self.lcdPower.setObjectName("lcdPower")
        #QGroupBox
        self.stationSelectorGroup = QtWidgets.QGroupBox(Dialog)
        self.stationSelectorGroup.setGeometry(QtCore.QRect(1770, 140, 141, 381))
        self.stationSelectorGroup.setObjectName("stationSelectorGroup")
        #QScrollArea
        self.stationListScrollArea = QtWidgets.QScrollArea(self.stationSelectorGroup)
        self.stationListScrollArea.setGeometry(QtCore.QRect(10, 30, 121, 331))
        self.stationListScrollArea.setWidgetResizable(True)
        self.stationListScrollArea.setObjectName("stationListScrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 119, 329))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.stationListScrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.checkBox = QtWidgets.QCheckBox(Dialog)
        self.checkBox.setGeometry(QtCore.QRect(10, 620, 161, 51))
        self.checkBox.setObjectName("checkBox")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.browseFileSelectButton.setText(_translate("Dialog", "Browse"))
        self.uploadTrackButton.setText(_translate("Dialog", "Upload Track Layout"))
        self.envTemp.setTitle(_translate("Dialog", "Env. Temperature (F)"))
        self.grad.setTitle(_translate("Dialog", "Block Grade (%)"))
        self.elev.setTitle(_translate("Dialog", "Elevation (m)"))
        self.blockSize.setTitle(_translate("Dialog", "Block Size (m)"))
        self.blockSelectorGroup.setTitle(_translate("Dialog", "Block Selector"))
        self.switches.setTitle(_translate("Dialog", "Switches"))
        self.signals.setTitle(_translate("Dialog", "Signals"))
        self.textBrowser.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-style:italic;\">Browse File to Upload .... </span></p></body></html>"))
        self.signals_2.setTitle(_translate("Dialog", "Failure Status"))
        self.brokenRailTxt.setText(_translate("Dialog", "Broken Rail Failure"))
        self.trackCircuitTxt.setText(_translate("Dialog", "Track Circuit Failure"))
        self.powerTxt.setText(_translate("Dialog", "Power Failure"))
        self.stationSelectorGroup.setTitle(_translate("Dialog", "Station List"))
        self.checkBox.setText(_translate("Dialog", "Track Heater"))