# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'trackModel_mainPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from services import trackBuilderService

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1920, 1080)
        Dialog.setMinimumSize(QtCore.QSize(1920, 500))
        self.graphicsView = QtWidgets.QGraphicsView(Dialog)
        self.graphicsView.setGeometry(QtCore.QRect(360, 140, 1251, 781))
        self.graphicsView.setObjectName("graphicsView")
        self.browseFileSelectButton = QtWidgets.QPushButton(Dialog)
        self.browseFileSelectButton.setGeometry(QtCore.QRect(1800, 850, 111, 61))
        self.browseFileSelectButton.setObjectName("browseFileSelectButton")
        #self.browseFileSelectButton.clicked.connect(lambda:trackBuilderService.readTrackFile())
        self.browseFileSelectButton.clicked.connect(lambda:print("This shit is TRASH"))
        self.uploadTrackButton = QtWidgets.QPushButton(Dialog)
        self.uploadTrackButton.setGeometry(QtCore.QRect(1620, 850, 171, 61))
        self.uploadTrackButton.setObjectName("uploadTrackButton")
        self.envTemp = QtWidgets.QGroupBox(Dialog)
        self.envTemp.setGeometry(QtCore.QRect(1770, 550, 141, 81))
        self.envTemp.setObjectName("envTemp")
        self.grad = QtWidgets.QGroupBox(Dialog)
        self.grad.setGeometry(QtCore.QRect(1620, 630, 141, 71))
        self.grad.setObjectName("grad")
        self.elev = QtWidgets.QGroupBox(Dialog)
        self.elev.setGeometry(QtCore.QRect(1770, 630, 141, 71))
        self.elev.setObjectName("elev")
        self.blockSize = QtWidgets.QGroupBox(Dialog)
        self.blockSize.setGeometry(QtCore.QRect(1620, 550, 141, 81))
        self.blockSize.setObjectName("blockSize")
        self.blockSelectorGroup = QtWidgets.QGroupBox(Dialog)
        self.blockSelectorGroup.setGeometry(QtCore.QRect(1620, 140, 151, 381))
        self.blockSelectorGroup.setObjectName("blockSelectorGroup")
        self.blockSelector = QtWidgets.QScrollArea(self.blockSelectorGroup)
        self.blockSelector.setGeometry(QtCore.QRect(10, 30, 121, 331))
        self.blockSelector.setWidgetResizable(True)
        self.blockSelector.setObjectName("blockSelector")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 119, 329))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.blockSelector.setWidget(self.scrollAreaWidgetContents)
        self.switches = QtWidgets.QGroupBox(Dialog)
        self.switches.setGeometry(QtCore.QRect(180, 350, 161, 251))
        self.switches.setObjectName("switches")
        self.signals = QtWidgets.QGroupBox(Dialog)
        self.signals.setGeometry(QtCore.QRect(10, 350, 161, 251))
        self.signals.setObjectName("signals")
        self.radioButton = QtWidgets.QRadioButton(Dialog)
        self.radioButton.setGeometry(QtCore.QRect(20, 600, 151, 61))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(Dialog)
        self.radioButton_2.setGeometry(QtCore.QRect(20, 660, 101, 41))
        self.radioButton_2.setObjectName("radioButton_2")
        self.textBrowser = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser.setGeometry(QtCore.QRect(1625, 810, 281, 31))
        self.textBrowser.setObjectName("textBrowser")
        self.signals_2 = QtWidgets.QGroupBox(Dialog)
        self.signals_2.setGeometry(QtCore.QRect(20, 130, 331, 211))
        self.signals_2.setObjectName("signals_2")
        self.blockSelectorGroup_2 = QtWidgets.QGroupBox(Dialog)
        self.blockSelectorGroup_2.setGeometry(QtCore.QRect(1770, 140, 141, 381))
        self.blockSelectorGroup_2.setObjectName("blockSelectorGroup_2")
        self.blockSelector_2 = QtWidgets.QScrollArea(self.blockSelectorGroup_2)
        self.blockSelector_2.setGeometry(QtCore.QRect(10, 30, 121, 331))
        self.blockSelector_2.setWidgetResizable(True)
        self.blockSelector_2.setObjectName("blockSelector_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 119, 329))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.blockSelector_2.setWidget(self.scrollAreaWidgetContents_2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.browseFileSelectButton.setText(_translate("Dialog", "Browse"))
        self.uploadTrackButton.setText(_translate("Dialog", "Upload Track Layout"))
        self.envTemp.setTitle(_translate("Dialog", "Env. Temperature"))
        self.grad.setTitle(_translate("Dialog", "Gradiation"))
        self.elev.setTitle(_translate("Dialog", "Elevation"))
        self.blockSize.setTitle(_translate("Dialog", "Block Size"))
        self.blockSelectorGroup.setTitle(_translate("Dialog", "Block Selector"))
        self.switches.setTitle(_translate("Dialog", "Switches"))
        self.signals.setTitle(_translate("Dialog", "Signals"))
        self.radioButton.setText(_translate("Dialog", "Heater"))
        self.radioButton_2.setText(_translate("Dialog", "Track Lights"))
        self.textBrowser.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-style:italic;\">Browse File to Upload .... </span></p></body></html>"))
        self.signals_2.setTitle(_translate("Dialog", "Failure Status"))
        self.blockSelectorGroup_2.setTitle(_translate("Dialog", "Station List"))
