# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'train_model_mainpage.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class UI(object):
    def setupUi(self, TrainModel):
        TrainModel.setObjectName("TrainModel")
        TrainModel.resize(1920, 1080)
        self.centralwidget = QtWidgets.QWidget(TrainModel)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setObjectName("gridLayout")
        self.authority_text = QtWidgets.QTextBrowser(self.centralwidget)
        self.authority_text.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.authority_text.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.authority_text.setObjectName("authority_text")
        self.gridLayout.addWidget(self.authority_text, 6, 2, 1, 1)
        self.currentTime_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.currentTime_label.setFont(font)
        self.currentTime_label.setTextFormat(QtCore.Qt.RichText)
        self.currentTime_label.setScaledContents(False)
        self.currentTime_label.setAlignment(QtCore.Qt.AlignCenter)
        self.currentTime_label.setObjectName("currentTime_label")
        self.gridLayout.addWidget(self.currentTime_label, 0, 0, 1, 1)
        self.currentSpeed_label_5 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.currentSpeed_label_5.setFont(font)
        self.currentSpeed_label_5.setTextFormat(QtCore.Qt.RichText)
        self.currentSpeed_label_5.setScaledContents(False)
        self.currentSpeed_label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.currentSpeed_label_5.setObjectName("currentSpeed_label_5")
        self.gridLayout.addWidget(self.currentSpeed_label_5, 4, 1, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.currentSpeed_label_6 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.currentSpeed_label_6.setFont(font)
        self.currentSpeed_label_6.setTextFormat(QtCore.Qt.RichText)
        self.currentSpeed_label_6.setScaledContents(False)
        self.currentSpeed_label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.currentSpeed_label_6.setObjectName("currentSpeed_label_6")
        self.gridLayout_3.addWidget(self.currentSpeed_label_6, 0, 0, 1, 1)
        self.currentSpeed_text_6 = QtWidgets.QTextBrowser(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(28)
        self.currentSpeed_text_6.setFont(font)
        self.currentSpeed_text_6.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.currentSpeed_text_6.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.currentSpeed_text_6.setObjectName("currentSpeed_text_6")
        self.gridLayout_3.addWidget(self.currentSpeed_text_6, 1, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_3, 7, 1, 1, 1)
        self.page_buttons_grid = QtWidgets.QGridLayout()
        self.page_buttons_grid.setObjectName("page_buttons_grid")
        self.properties_button = QtWidgets.QPushButton(self.centralwidget)
        self.properties_button.setObjectName("properties_button")
        self.page_buttons_grid.addWidget(self.properties_button, 2, 0, 1, 1)
        self.passengerPage_button = QtWidgets.QPushButton(self.centralwidget)
        self.passengerPage_button.setObjectName("passengerPage_button")
        self.page_buttons_grid.addWidget(self.passengerPage_button, 0, 0, 1, 1)
        self.diagnostics_button = QtWidgets.QPushButton(self.centralwidget)
        self.diagnostics_button.setObjectName("diagnostics_button")
        self.page_buttons_grid.addWidget(self.diagnostics_button, 1, 0, 1, 1)
        self.limits_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.limits_label.setFont(font)
        self.limits_label.setTextFormat(QtCore.Qt.RichText)
        self.limits_label.setScaledContents(False)
        self.limits_label.setAlignment(QtCore.Qt.AlignCenter)
        self.limits_label.setObjectName("limits_label")
        self.page_buttons_grid.addWidget(self.limits_label, 3, 0, 1, 1)
        self.gridLayout.addLayout(self.page_buttons_grid, 1, 3, 1, 1)
        self.speedLimit_text = QtWidgets.QTextBrowser(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(28)
        self.speedLimit_text.setFont(font)
        self.speedLimit_text.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.speedLimit_text.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.speedLimit_text.setObjectName("speedLimit_text")
        self.gridLayout.addWidget(self.speedLimit_text, 1, 1, 1, 1)
        self.arrivalTime_text = QtWidgets.QTextBrowser(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(28)
        self.arrivalTime_text.setFont(font)
        self.arrivalTime_text.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.arrivalTime_text.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.arrivalTime_text.setObjectName("arrivalTime_text")
        self.gridLayout.addWidget(self.arrivalTime_text, 6, 0, 1, 1)
        self.departureTime_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.departureTime_label.setFont(font)
        self.departureTime_label.setScaledContents(False)
        self.departureTime_label.setAlignment(QtCore.Qt.AlignCenter)
        self.departureTime_label.setObjectName("departureTime_label")
        self.gridLayout.addWidget(self.departureTime_label, 2, 0, 1, 1)
        self.arrivalTime_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.arrivalTime_label.setFont(font)
        self.arrivalTime_label.setTextFormat(QtCore.Qt.RichText)
        self.arrivalTime_label.setScaledContents(False)
        self.arrivalTime_label.setAlignment(QtCore.Qt.AlignCenter)
        self.arrivalTime_label.setObjectName("arrivalTime_label")
        self.gridLayout.addWidget(self.arrivalTime_label, 4, 0, 1, 1)
        self.brakeStatus_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.brakeStatus_label.setFont(font)
        self.brakeStatus_label.setTextFormat(QtCore.Qt.RichText)
        self.brakeStatus_label.setScaledContents(False)
        self.brakeStatus_label.setAlignment(QtCore.Qt.AlignCenter)
        self.brakeStatus_label.setObjectName("brakeStatus_label")
        self.gridLayout.addWidget(self.brakeStatus_label, 0, 2, 1, 1)
        self.decLimit_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.decLimit_label.setFont(font)
        self.decLimit_label.setTextFormat(QtCore.Qt.RichText)
        self.decLimit_label.setScaledContents(False)
        self.decLimit_label.setAlignment(QtCore.Qt.AlignCenter)
        self.decLimit_label.setObjectName("decLimit_label")
        self.gridLayout.addWidget(self.decLimit_label, 4, 3, 1, 1)
        self.authority_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.authority_label.setFont(font)
        self.authority_label.setTextFormat(QtCore.Qt.RichText)
        self.authority_label.setScaledContents(False)
        self.authority_label.setAlignment(QtCore.Qt.AlignCenter)
        self.authority_label.setObjectName("authority_label")
        self.gridLayout.addWidget(self.authority_label, 4, 2, 1, 1)
        self.currentSpeed_label_4 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.currentSpeed_label_4.setFont(font)
        self.currentSpeed_label_4.setTextFormat(QtCore.Qt.RichText)
        self.currentSpeed_label_4.setScaledContents(False)
        self.currentSpeed_label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.currentSpeed_label_4.setObjectName("currentSpeed_label_4")
        self.gridLayout.addWidget(self.currentSpeed_label_4, 2, 1, 1, 1)
        self.speedLimit_label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.speedLimit_label_2.setFont(font)
        self.speedLimit_label_2.setTextFormat(QtCore.Qt.RichText)
        self.speedLimit_label_2.setScaledContents(False)
        self.speedLimit_label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.speedLimit_label_2.setObjectName("speedLimit_label_2")
        self.gridLayout.addWidget(self.speedLimit_label_2, 0, 1, 1, 1)
        self.departureTime_text = QtWidgets.QTextBrowser(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(28)
        self.departureTime_text.setFont(font)
        self.departureTime_text.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.departureTime_text.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.departureTime_text.setObjectName("departureTime_text")
        self.gridLayout.addWidget(self.departureTime_text, 3, 0, 1, 1)
        self.failureStatus_grid = QtWidgets.QGridLayout()
        self.failureStatus_grid.setObjectName("failureStatus_grid")
        self.brakeFailureStatus_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.brakeFailureStatus_label.setFont(font)
        self.brakeFailureStatus_label.setTextFormat(QtCore.Qt.RichText)
        self.brakeFailureStatus_label.setScaledContents(False)
        self.brakeFailureStatus_label.setAlignment(QtCore.Qt.AlignCenter)
        self.brakeFailureStatus_label.setObjectName("brakeFailureStatus_label")
        self.failureStatus_grid.addWidget(self.brakeFailureStatus_label, 1, 0, 1, 1)
        self.signalPickupFailure_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.signalPickupFailure_label.setFont(font)
        self.signalPickupFailure_label.setTextFormat(QtCore.Qt.RichText)
        self.signalPickupFailure_label.setScaledContents(False)
        self.signalPickupFailure_label.setAlignment(QtCore.Qt.AlignCenter)
        self.signalPickupFailure_label.setObjectName("signalPickupFailure_label")
        self.failureStatus_grid.addWidget(self.signalPickupFailure_label, 2, 0, 1, 1)
        self.dial_4 = QtWidgets.QDial(self.centralwidget)
        self.dial_4.setObjectName("dial_4")

        # self.serviceBrakes_circle = QtGui.QPainter()
        # pen = QtGui.QPen()
        # pen.setBrush(QtGui.QColor.black)
        # pen.setWidth(5)
        # pen.SetStyle(QtCore.Qt.SolidLine)

        # self.serviceBrakes_circle.setPen(pen)
        # self.serviceBrakes_circle.drawEllipse(100, 100, 100, 100)


        # self.failureStatus_grid.addWidget(self.serviceBrakes_circle, 1, 1, 1, 1)
        #self.failureStatus_grid.addWidget(self.dial_4, 1, 1, 1, 1)
        self.dial_3 = QtWidgets.QDial(self.centralwidget)
        self.dial_3.setObjectName("dial_3")
        self.failureStatus_grid.addWidget(self.dial_3, 0, 1, 1, 1)
        self.engineFailure_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.engineFailure_label.setFont(font)
        self.engineFailure_label.setTextFormat(QtCore.Qt.RichText)
        self.engineFailure_label.setScaledContents(False)
        self.engineFailure_label.setAlignment(QtCore.Qt.AlignCenter)
        self.engineFailure_label.setObjectName("engineFailure_label")
        self.failureStatus_grid.addWidget(self.engineFailure_label, 0, 0, 1, 1)
        self.dial_5 = QtWidgets.QDial(self.centralwidget)
        self.dial_5.setObjectName("dial_5")
        self.failureStatus_grid.addWidget(self.dial_5, 2, 1, 1, 1)
        self.gridLayout.addLayout(self.failureStatus_grid, 3, 2, 1, 1)
        self.block_grid = QtWidgets.QGridLayout()
        self.block_grid.setObjectName("block_grid")
        self.block_text = QtWidgets.QTextBrowser(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(28)
        self.block_text.setFont(font)
        self.block_text.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.block_text.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.block_text.setObjectName("block_text")
        self.block_grid.addWidget(self.block_text, 1, 0, 1, 1)
        self.block_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.block_label.setFont(font)
        self.block_label.setTextFormat(QtCore.Qt.RichText)
        self.block_label.setScaledContents(False)
        self.block_label.setAlignment(QtCore.Qt.AlignCenter)
        self.block_label.setObjectName("block_label")
        self.block_grid.addWidget(self.block_label, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.block_grid, 7, 2, 1, 1)
        self.currentTime_text = QtWidgets.QTextBrowser(self.centralwidget)
        self.currentTime_text.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.currentTime_text.sizePolicy().hasHeightForWidth())
        self.currentTime_text.setSizePolicy(sizePolicy)
        self.currentTime_text.setMinimumSize(QtCore.QSize(1, 1))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(28)
        self.currentTime_text.setFont(font)
        self.currentTime_text.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.currentTime_text.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.currentTime_text.setObjectName("currentTime_text")
        self.gridLayout.addWidget(self.currentTime_text, 1, 0, 1, 1)
        self.currentSpeed_text = QtWidgets.QTextBrowser(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(28)
        self.currentSpeed_text.setFont(font)
        self.currentSpeed_text.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.currentSpeed_text.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.currentSpeed_text.setObjectName("currentSpeed_text")
        self.gridLayout.addWidget(self.currentSpeed_text, 3, 1, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.passengers_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.passengers_label.setFont(font)
        self.passengers_label.setTextFormat(QtCore.Qt.RichText)
        self.passengers_label.setScaledContents(False)
        self.passengers_label.setAlignment(QtCore.Qt.AlignCenter)
        self.passengers_label.setObjectName("passengers_label")
        self.gridLayout_2.addWidget(self.passengers_label, 0, 0, 1, 1)
        self.temp_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.temp_label.setFont(font)
        self.temp_label.setTextFormat(QtCore.Qt.RichText)
        self.temp_label.setScaledContents(False)
        self.temp_label.setAlignment(QtCore.Qt.AlignCenter)
        self.temp_label.setObjectName("temp_label")
        self.gridLayout_2.addWidget(self.temp_label, 0, 1, 1, 1)
        self.passengers_text = QtWidgets.QTextBrowser(self.centralwidget)
        self.passengers_text.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.passengers_text.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.passengers_text.setObjectName("passengers_text")
        self.gridLayout_2.addWidget(self.passengers_text, 1, 0, 1, 1)
        self.temp_text = QtWidgets.QTextBrowser(self.centralwidget)
        self.temp_text.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.temp_text.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.temp_text.setObjectName("temp_text")
        self.gridLayout_2.addWidget(self.temp_text, 1, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 7, 0, 1, 1)
        self.suggestedSpeed_text = QtWidgets.QTextBrowser(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(28)
        self.suggestedSpeed_text.setFont(font)
        self.suggestedSpeed_text.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.suggestedSpeed_text.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.suggestedSpeed_text.setObjectName("suggestedSpeed_text")
        self.gridLayout.addWidget(self.suggestedSpeed_text, 6, 1, 1, 1)
        self.brakeStatus_grid = QtWidgets.QGridLayout()
        self.brakeStatus_grid.setObjectName("brakeStatus_grid")
        self.dial_2 = QtWidgets.QDial(self.centralwidget)
        self.dial_2.setObjectName("dial_2")
        self.brakeStatus_grid.addWidget(self.dial_2, 1, 1, 1, 1)
        self.dial = QtWidgets.QDial(self.centralwidget)
        self.dial.setObjectName("dial")
        self.brakeStatus_grid.addWidget(self.dial, 0, 1, 1, 1)
        self.serviceBrakes_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.serviceBrakes_label.setFont(font)
        self.serviceBrakes_label.setTextFormat(QtCore.Qt.RichText)
        self.serviceBrakes_label.setScaledContents(False)
        self.serviceBrakes_label.setAlignment(QtCore.Qt.AlignCenter)
        self.serviceBrakes_label.setObjectName("serviceBrakes_label")
        self.brakeStatus_grid.addWidget(self.serviceBrakes_label, 0, 0, 1, 1)
        self.emergencyBrakes_label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.emergencyBrakes_label.sizePolicy().hasHeightForWidth())
        self.emergencyBrakes_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.emergencyBrakes_label.setFont(font)
        self.emergencyBrakes_label.setTextFormat(QtCore.Qt.RichText)
        self.emergencyBrakes_label.setScaledContents(False)
        self.emergencyBrakes_label.setAlignment(QtCore.Qt.AlignCenter)
        self.emergencyBrakes_label.setObjectName("emergencyBrakes_label")
        self.brakeStatus_grid.addWidget(self.emergencyBrakes_label, 1, 0, 1, 1)
        self.gridLayout.addLayout(self.brakeStatus_grid, 1, 2, 1, 1)
        self.doors_grid = QtWidgets.QGridLayout()
        self.doors_grid.setObjectName("doors_grid")
        self.doors_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.doors_label.setFont(font)
        self.doors_label.setTextFormat(QtCore.Qt.RichText)
        self.doors_label.setScaledContents(False)
        self.doors_label.setAlignment(QtCore.Qt.AlignCenter)
        self.doors_label.setObjectName("doors_label")
        self.doors_grid.addWidget(self.doors_label, 0, 0, 1, 1)
        self.doors_text = QtWidgets.QTextBrowser(self.centralwidget)
        self.doors_text.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.doors_text.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.doors_text.setObjectName("doors_text")
        self.doors_grid.addWidget(self.doors_text, 1, 0, 1, 1)
        self.gridLayout.addLayout(self.doors_grid, 7, 3, 1, 1)
        self.decLimit_text = QtWidgets.QTextBrowser(self.centralwidget)
        self.decLimit_text.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.decLimit_text.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.decLimit_text.setObjectName("decLimit_text")
        self.gridLayout.addWidget(self.decLimit_text, 6, 3, 1, 1)
        self.failureStatus_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.failureStatus_label.setFont(font)
        self.failureStatus_label.setTextFormat(QtCore.Qt.RichText)
        self.failureStatus_label.setScaledContents(False)
        self.failureStatus_label.setAlignment(QtCore.Qt.AlignCenter)
        self.failureStatus_label.setObjectName("failureStatus_label")
        self.gridLayout.addWidget(self.failureStatus_label, 2, 2, 1, 1)
        self.accLimit_grid = QtWidgets.QGridLayout()
        self.accLimit_grid.setObjectName("accLimit_grid")
        self.accLimit_text = QtWidgets.QTextBrowser(self.centralwidget)
        self.accLimit_text.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.accLimit_text.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.accLimit_text.setObjectName("accLimit_text")
        self.accLimit_grid.addWidget(self.accLimit_text, 1, 0, 1, 1)
        self.gridLayout.addLayout(self.accLimit_grid, 3, 3, 1, 1)
        self.accLimit_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.accLimit_label.setFont(font)
        self.accLimit_label.setTextFormat(QtCore.Qt.RichText)
        self.accLimit_label.setScaledContents(False)
        self.accLimit_label.setAlignment(QtCore.Qt.AlignCenter)
        self.accLimit_label.setObjectName("accLimit_label")
        self.gridLayout.addWidget(self.accLimit_label, 2, 3, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout, 0, 0, 1, 1)
        TrainModel.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(TrainModel)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1920, 21))
        self.menubar.setObjectName("menubar")
        self.menufdf = QtWidgets.QMenu(self.menubar)
        self.menufdf.setObjectName("menufdf")
        self.menuDiagnostics_Page = QtWidgets.QMenu(self.menubar)
        self.menuDiagnostics_Page.setObjectName("menuDiagnostics_Page")
        self.menuProperties_Page = QtWidgets.QMenu(self.menubar)
        self.menuProperties_Page.setObjectName("menuProperties_Page")
        self.menuTesting_Page = QtWidgets.QMenu(self.menubar)
        self.menuTesting_Page.setObjectName("menuTesting_Page")
        TrainModel.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(TrainModel)
        self.statusbar.setObjectName("statusbar")
        TrainModel.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menufdf.menuAction())
        self.menubar.addAction(self.menuDiagnostics_Page.menuAction())
        self.menubar.addAction(self.menuProperties_Page.menuAction())
        self.menubar.addAction(self.menuTesting_Page.menuAction())

        self.retranslateUi(TrainModel)
        QtCore.QMetaObject.connectSlotsByName(TrainModel)

    def retranslateUi(self, TrainModel):
        _translate = QtCore.QCoreApplication.translate
        TrainModel.setWindowTitle(_translate("TrainModel", "MainWindow"))
        self.authority_text.setHtml(_translate("TrainModel", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt;\">60 mi</span></p></body></html>"))
        self.currentTime_label.setText(_translate("TrainModel", "Current Time"))
        self.currentSpeed_label_5.setText(_translate("TrainModel", "Suggested Speed"))
        self.currentSpeed_label_6.setText(_translate("TrainModel", "Power"))
        self.currentSpeed_text_6.setHtml(_translate("TrainModel", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:28pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:16pt;\">2000 kW</span></p></body></html>"))
        self.properties_button.setText(_translate("TrainModel", "Properties Page"))
        self.passengerPage_button.setText(_translate("TrainModel", "Passenger Page"))
        self.diagnostics_button.setText(_translate("TrainModel", "Diagnostics Page"))
        self.limits_label.setText(_translate("TrainModel", "Limits"))
        self.speedLimit_text.setHtml(_translate("TrainModel", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:28pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:16pt;\">85 mph</span></p></body></html>"))
        self.arrivalTime_text.setHtml(_translate("TrainModel", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:28pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:16pt;\">12:00:00</span></p></body></html>"))
        self.departureTime_label.setText(_translate("TrainModel", "Departure Time"))
        self.arrivalTime_label.setText(_translate("TrainModel", "Arrival Time"))
        self.brakeStatus_label.setText(_translate("TrainModel", "Brake Status"))
        self.decLimit_label.setText(_translate("TrainModel", "Deceleration Limit:"))
        self.authority_label.setText(_translate("TrainModel", "Authority"))
        self.currentSpeed_label_4.setText(_translate("TrainModel", "Current Speed"))
        self.speedLimit_label_2.setText(_translate("TrainModel", "Speed Limit"))
        self.departureTime_text.setHtml(_translate("TrainModel", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:28pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:16pt;\">12:00:00</span></p></body></html>"))
        self.brakeFailureStatus_label.setText(_translate("TrainModel", "Brake Status:"))
        self.signalPickupFailure_label.setText(_translate("TrainModel", "Signal Pickup Status:"))
        self.engineFailure_label.setText(_translate("TrainModel", "Engine Status:"))
        self.block_text.setHtml(_translate("TrainModel", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:28pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:16pt;\">4A</span></p></body></html>"))
        self.block_label.setText(_translate("TrainModel", "Block"))
        self.currentTime_text.setHtml(_translate("TrainModel", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:28pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:16pt;\">12:00:00</span></p></body></html>"))
        self.currentSpeed_text.setHtml(_translate("TrainModel", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:28pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:16pt;\">75 mph</span></p></body></html>"))
        self.passengers_label.setText(_translate("TrainModel", "Passengers"))
        self.temp_label.setText(_translate("TrainModel", "Temp"))
        self.passengers_text.setHtml(_translate("TrainModel", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt;\">200</span></p></body></html>"))
        self.temp_text.setHtml(_translate("TrainModel", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt;\">72 F</span></p></body></html>"))
        self.suggestedSpeed_text.setHtml(_translate("TrainModel", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:28pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:16pt;\">80 mph</span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:16pt;\"><br /></p></body></html>"))
        self.serviceBrakes_label.setText(_translate("TrainModel", "Service Brakes:"))
        self.emergencyBrakes_label.setText(_translate("TrainModel", "Emergency Brakes:"))
        self.doors_label.setText(_translate("TrainModel", "Doors"))
        self.doors_text.setHtml(_translate("TrainModel", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt;\">Closed</span></p></body></html>"))
        self.decLimit_text.setHtml(_translate("TrainModel", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt;\">15 m/s^2</span></p></body></html>"))
        self.failureStatus_label.setText(_translate("TrainModel", "Failure Status"))
        self.accLimit_text.setHtml(_translate("TrainModel", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt;\">10 m/s^2</span></p></body></html>"))
        self.accLimit_label.setText(_translate("TrainModel", "Acceleration Limit:"))
        self.menufdf.setTitle(_translate("TrainModel", "Passenger Page"))
        self.menuDiagnostics_Page.setTitle(_translate("TrainModel", "Diagnostics Page"))
        self.menuProperties_Page.setTitle(_translate("TrainModel", "Properties Page"))
        self.menuTesting_Page.setTitle(_translate("TrainModel", "Testing Page"))

def paintEvent(self, event):
        super().paintEvent(event)
        if self.should_paint_circle:
            painter = QtGui.QPainter(self)
            painter.setRenderHint(QPainter.Antialiasing)
            painter.setPen(QPen(Qt.black, 5, Qt.SolidLine))
            painter.drawEllipse(100, 100, 100, 100)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TrainModel = QtWidgets.QMainWindow()
    ui = UI()
    ui.setupUi(TrainModel)
    TrainModel.show()
    sys.exit(app.exec_())