# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'train_model_mainpage_updated.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import sys
sys.path.append("..")

from Shared.connections import *

class Mainpage_UI(object):
    def setupUi(self, TrainModel, currentTrainNum):
        self.currentTrainNum = currentTrainNum
        TrainModel.setObjectName("TrainModel")
        TrainModel.resize(1920, 1080)
        self.centralwidget = QtWidgets.QWidget(TrainModel)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 4, 4, 1, 1)
        self.currentTime_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.currentTime_label.setFont(font)
        self.currentTime_label.setTextFormat(QtCore.Qt.RichText)
        self.currentTime_label.setScaledContents(False)
        self.currentTime_label.setAlignment(QtCore.Qt.AlignCenter)
        self.currentTime_label.setObjectName("currentTime_label")
        self.gridLayout.addWidget(self.currentTime_label, 0, 0, 1, 1)
        self.doors_grid = QtWidgets.QGridLayout()
        self.doors_grid.setObjectName("doors_grid")
        self.doors_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.doors_label.setFont(font)
        self.doors_label.setTextFormat(QtCore.Qt.RichText)
        self.doors_label.setScaledContents(False)
        self.doors_label.setAlignment(QtCore.Qt.AlignCenter)
        self.doors_label.setObjectName("doors_label")
        self.doors_grid.addWidget(self.doors_label, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.doors_grid, 8, 4, 1, 1)
        self.brakeStatus_grid = QtWidgets.QGridLayout()
        self.brakeStatus_grid.setObjectName("brakeStatus_grid")
        self.serviceBrakes_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.serviceBrakes_label.setFont(font)
        self.serviceBrakes_label.setTextFormat(QtCore.Qt.RichText)
        self.serviceBrakes_label.setScaledContents(False)
        self.serviceBrakes_label.setAlignment(QtCore.Qt.AlignCenter)
        self.serviceBrakes_label.setObjectName("serviceBrakes_label")
        self.brakeStatus_grid.addWidget(self.serviceBrakes_label, 0, 0, 1, 1)
        self.emergencyBrakes_label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.emergencyBrakes_label.sizePolicy().hasHeightForWidth())
        self.emergencyBrakes_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.emergencyBrakes_label.setFont(font)
        self.emergencyBrakes_label.setTextFormat(QtCore.Qt.RichText)
        self.emergencyBrakes_label.setScaledContents(False)
        self.emergencyBrakes_label.setAlignment(QtCore.Qt.AlignCenter)
        self.emergencyBrakes_label.setObjectName("emergencyBrakes_label")
        self.brakeStatus_grid.addWidget(self.emergencyBrakes_label, 1, 0, 1, 1)
        self.emergencyBrakes_indicator = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.emergencyBrakes_indicator.setFont(font)
        self.emergencyBrakes_indicator.setAutoFillBackground(False)
        self.emergencyBrakes_indicator.setAlignment(QtCore.Qt.AlignCenter)
        self.emergencyBrakes_indicator.setObjectName("emergencyBrakes_indicator")
        self.brakeStatus_grid.addWidget(self.emergencyBrakes_indicator, 1, 1, 1, 1)
        self.serviceBrakes_indicator = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.serviceBrakes_indicator.setFont(font)
        self.serviceBrakes_indicator.setAlignment(QtCore.Qt.AlignCenter)
        self.serviceBrakes_indicator.setObjectName("serviceBrakes_indicator")
        self.brakeStatus_grid.addWidget(self.serviceBrakes_indicator, 0, 1, 1, 1)
        self.gridLayout.addLayout(self.brakeStatus_grid, 1, 3, 1, 1)
        self.brakeStatus_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.brakeStatus_label.setFont(font)
        self.brakeStatus_label.setTextFormat(QtCore.Qt.RichText)
        self.brakeStatus_label.setScaledContents(False)
        self.brakeStatus_label.setAlignment(QtCore.Qt.AlignCenter)
        self.brakeStatus_label.setObjectName("brakeStatus_label")
        self.gridLayout.addWidget(self.brakeStatus_label, 0, 3, 1, 1)
        self.page_buttons_grid = QtWidgets.QGridLayout()
        self.page_buttons_grid.setObjectName("page_buttons_grid")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.page_buttons_grid.addItem(spacerItem, 1, 0, 1, 1)
        self.passengerPage_button = QtWidgets.QPushButton(self.centralwidget)
        self.passengerPage_button.setObjectName("passengerPage_button")
        self.page_buttons_grid.addWidget(self.passengerPage_button, 0, 1, 1, 1)
        self.diagnostics_button = QtWidgets.QPushButton(self.centralwidget)
        self.diagnostics_button.setObjectName("diagnostics_button")
        self.page_buttons_grid.addWidget(self.diagnostics_button, 1, 1, 1, 1)
        #self.propertiesPage_button = QtWidgets.QPushButton(self.centralwidget)
        #self.propertiesPage_button.setObjectName("propertiesPage_button")
        #self.page_buttons_grid.addWidget(self.propertiesPage_button, 2, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.page_buttons_grid.addItem(spacerItem1, 1, 2, 1, 1)
        self.testingPage_button = QtWidgets.QPushButton(self.centralwidget)
        self.testingPage_button.setObjectName("testingPage_button")
        self.page_buttons_grid.addWidget(self.testingPage_button, 3, 1, 1, 1)
        self.gridLayout.addLayout(self.page_buttons_grid, 1, 4, 1, 1)
        self.departureTime_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.departureTime_label.setFont(font)
        self.departureTime_label.setScaledContents(False)
        self.departureTime_label.setAlignment(QtCore.Qt.AlignCenter)
        self.departureTime_label.setObjectName("departureTime_label")
        self.gridLayout.addWidget(self.departureTime_label, 2, 0, 1, 1)
        self.currentSpeed_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.currentSpeed_label.setFont(font)
        self.currentSpeed_label.setTextFormat(QtCore.Qt.RichText)
        self.currentSpeed_label.setScaledContents(False)
        self.currentSpeed_label.setAlignment(QtCore.Qt.AlignCenter)
        self.currentSpeed_label.setObjectName("currentSpeed_label")
        self.gridLayout.addWidget(self.currentSpeed_label, 0, 2, 1, 1)
        self.speed_grid = QtWidgets.QGridLayout()
        self.speed_grid.setObjectName("speed_grid")
        self.suggestedSpeed_text = QtWidgets.QTextBrowser(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(28)
        self.suggestedSpeed_text.setFont(font)
        self.suggestedSpeed_text.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.suggestedSpeed_text.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.suggestedSpeed_text.setObjectName("suggestedSpeed_text")
        self.speed_grid.addWidget(self.suggestedSpeed_text, 2, 0, 1, 1)
        self.commandedSpeed_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.commandedSpeed_label.setFont(font)
        self.commandedSpeed_label.setAlignment(QtCore.Qt.AlignCenter)
        self.commandedSpeed_label.setObjectName("commandedSpeed_label")
        self.speed_grid.addWidget(self.commandedSpeed_label, 3, 0, 1, 1)
        self.commandedSpeed_text = QtWidgets.QTextBrowser(self.centralwidget)
        self.commandedSpeed_text.setObjectName("commandedSpeed_text")
        self.speed_grid.addWidget(self.commandedSpeed_text, 4, 0, 1, 1)
        self.gridLayout.addLayout(self.speed_grid, 3, 2, 1, 1)
        self.time_grid = QtWidgets.QGridLayout()
        self.time_grid.setObjectName("time_grid")
        self.departureTime_text = QtWidgets.QTextBrowser(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(28)
        self.departureTime_text.setFont(font)
        self.departureTime_text.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.departureTime_text.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.departureTime_text.setObjectName("departureTime_text")
        self.time_grid.addWidget(self.departureTime_text, 0, 0, 1, 1)
        self.arrivalTime_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.arrivalTime_label.setFont(font)
        self.arrivalTime_label.setTextFormat(QtCore.Qt.RichText)
        self.arrivalTime_label.setScaledContents(False)
        self.arrivalTime_label.setAlignment(QtCore.Qt.AlignCenter)
        self.arrivalTime_label.setObjectName("arrivalTime_label")
        self.time_grid.addWidget(self.arrivalTime_label, 1, 0, 1, 1)
        self.arrivalTime_text = QtWidgets.QTextBrowser(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(28)
        self.arrivalTime_text.setFont(font)
        self.arrivalTime_text.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.arrivalTime_text.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.arrivalTime_text.setObjectName("arrivalTime_text")
        self.time_grid.addWidget(self.arrivalTime_text, 2, 0, 1, 1)
        self.gridLayout.addLayout(self.time_grid, 3, 0, 1, 1)
        self.temp_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.temp_label.setFont(font)
        self.temp_label.setTextFormat(QtCore.Qt.RichText)
        self.temp_label.setScaledContents(False)
        self.temp_label.setAlignment(QtCore.Qt.AlignCenter)
        self.temp_label.setObjectName("temp_label")
        self.gridLayout.addWidget(self.temp_label, 8, 0, 1, 1)
        self.suggestedSpeed_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.suggestedSpeed_label.setFont(font)
        self.suggestedSpeed_label.setTextFormat(QtCore.Qt.RichText)
        self.suggestedSpeed_label.setScaledContents(False)
        self.suggestedSpeed_label.setAlignment(QtCore.Qt.AlignCenter)
        self.suggestedSpeed_label.setObjectName("suggestedSpeed_label")
        self.gridLayout.addWidget(self.suggestedSpeed_label, 2, 2, 1, 1)
        self.authority_text = QtWidgets.QTextBrowser(self.centralwidget)
        self.authority_text.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.authority_text.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.authority_text.setObjectName("authority_text")
        self.gridLayout.addWidget(self.authority_text, 6, 3, 1, 1)
        self.power_text = QtWidgets.QTextBrowser(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(28)
        self.power_text.setFont(font)
        self.power_text.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.power_text.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.power_text.setObjectName("power_text")
        self.gridLayout.addWidget(self.power_text, 9, 2, 1, 1)
        self.power_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.power_label.setFont(font)
        self.power_label.setTextFormat(QtCore.Qt.RichText)
        self.power_label.setScaledContents(False)
        self.power_label.setAlignment(QtCore.Qt.AlignCenter)
        self.power_label.setObjectName("power_label")
        self.gridLayout.addWidget(self.power_label, 8, 2, 1, 1)
        self.passengers_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.passengers_label.setFont(font)
        self.passengers_label.setTextFormat(QtCore.Qt.RichText)
        self.passengers_label.setScaledContents(False)
        self.passengers_label.setAlignment(QtCore.Qt.AlignCenter)
        self.passengers_label.setObjectName("passengers_label")
        self.gridLayout.addWidget(self.passengers_label, 4, 0, 1, 1)
        self.speedLimit_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.speedLimit_label.setFont(font)
        self.speedLimit_label.setTextFormat(QtCore.Qt.RichText)
        self.speedLimit_label.setScaledContents(False)
        self.speedLimit_label.setAlignment(QtCore.Qt.AlignCenter)
        self.speedLimit_label.setObjectName("speedLimit_label")
        self.gridLayout.addWidget(self.speedLimit_label, 4, 2, 1, 1)
        self.currentSpeed_text = QtWidgets.QTextBrowser(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(28)
        self.currentSpeed_text.setFont(font)
        self.currentSpeed_text.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.currentSpeed_text.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.currentSpeed_text.setObjectName("currentSpeed_text")
        self.gridLayout.addWidget(self.currentSpeed_text, 1, 2, 1, 1)
        self.accLimit_grid = QtWidgets.QGridLayout()
        self.accLimit_grid.setObjectName("accLimit_grid")
        self.nextStation_text = QtWidgets.QTextBrowser(self.centralwidget)
        self.nextStation_text.setObjectName("nextStation_text")
        self.accLimit_grid.addWidget(self.nextStation_text, 3, 0, 1, 1)
        self.nextStation_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.nextStation_label.setFont(font)
        self.nextStation_label.setAlignment(QtCore.Qt.AlignCenter)
        self.nextStation_label.setObjectName("nextStation_label")
        self.accLimit_grid.addWidget(self.nextStation_label, 2, 0, 1, 1)
        self.trainNum_text = QtWidgets.QTextBrowser(self.centralwidget)
        self.trainNum_text.setObjectName("trainNum_text")
        self.accLimit_grid.addWidget(self.trainNum_text, 1, 0, 1, 1)
        self.gridLayout.addLayout(self.accLimit_grid, 3, 4, 1, 1)
        self.failureStatus_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.failureStatus_label.setFont(font)
        self.failureStatus_label.setTextFormat(QtCore.Qt.RichText)
        self.failureStatus_label.setScaledContents(False)
        self.failureStatus_label.setAlignment(QtCore.Qt.AlignCenter)
        self.failureStatus_label.setObjectName("failureStatus_label")
        self.gridLayout.addWidget(self.failureStatus_label, 2, 3, 1, 1)
        self.passengers_text = QtWidgets.QTextBrowser(self.centralwidget)
        self.passengers_text.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.passengers_text.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.passengers_text.setObjectName("passengers_text")
        self.gridLayout.addWidget(self.passengers_text, 6, 0, 1, 1)
        self.temp_text = QtWidgets.QTextBrowser(self.centralwidget)
        self.temp_text.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.temp_text.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.temp_text.setObjectName("temp_text")
        self.gridLayout.addWidget(self.temp_text, 9, 0, 1, 1)
        self.block_text = QtWidgets.QTextBrowser(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(28)
        self.block_text.setFont(font)
        self.block_text.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.block_text.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.block_text.setObjectName("block_text")
        self.gridLayout.addWidget(self.block_text, 9, 3, 1, 1)
        self.speedLimit_text = QtWidgets.QTextBrowser(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(28)
        self.speedLimit_text.setFont(font)
        self.speedLimit_text.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.speedLimit_text.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.speedLimit_text.setObjectName("speedLimit_text")
        self.gridLayout.addWidget(self.speedLimit_text, 6, 2, 1, 1)
        self.failureStatus_grid = QtWidgets.QGridLayout()
        self.failureStatus_grid.setObjectName("failureStatus_grid")
        self.brakeFailureStatus_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.brakeFailureStatus_label.setFont(font)
        self.brakeFailureStatus_label.setTextFormat(QtCore.Qt.RichText)
        self.brakeFailureStatus_label.setScaledContents(False)
        self.brakeFailureStatus_label.setAlignment(QtCore.Qt.AlignCenter)
        self.brakeFailureStatus_label.setObjectName("brakeFailureStatus_label")
        self.failureStatus_grid.addWidget(self.brakeFailureStatus_label, 1, 0, 1, 1)
        self.signalPickupFailure_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.signalPickupFailure_label.setFont(font)
        self.signalPickupFailure_label.setTextFormat(QtCore.Qt.RichText)
        self.signalPickupFailure_label.setScaledContents(False)
        self.signalPickupFailure_label.setAlignment(QtCore.Qt.AlignCenter)
        self.signalPickupFailure_label.setObjectName("signalPickupFailure_label")
        self.failureStatus_grid.addWidget(self.signalPickupFailure_label, 2, 0, 1, 1)
        self.engineFailure_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.engineFailure_label.setFont(font)
        self.engineFailure_label.setTextFormat(QtCore.Qt.RichText)
        self.engineFailure_label.setScaledContents(False)
        self.engineFailure_label.setAlignment(QtCore.Qt.AlignCenter)
        self.engineFailure_label.setObjectName("engineFailure_label")
        self.failureStatus_grid.addWidget(self.engineFailure_label, 0, 0, 1, 1)
        self.brakeStatus_indicator = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.brakeStatus_indicator.setFont(font)
        self.brakeStatus_indicator.setAlignment(QtCore.Qt.AlignCenter)
        self.brakeStatus_indicator.setObjectName("brakeStatus_indicator")
        self.failureStatus_grid.addWidget(self.brakeStatus_indicator, 1, 1, 1, 1)
        self.engineStatus_indicator = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.engineStatus_indicator.setFont(font)
        self.engineStatus_indicator.setAlignment(QtCore.Qt.AlignCenter)
        self.engineStatus_indicator.setObjectName("engineStatus_indicator")
        self.failureStatus_grid.addWidget(self.engineStatus_indicator, 0, 1, 1, 1)
        self.signalpickupStatus_indicator = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.signalpickupStatus_indicator.setFont(font)
        self.signalpickupStatus_indicator.setAlignment(QtCore.Qt.AlignCenter)
        self.signalpickupStatus_indicator.setObjectName("signalpickupStatus_indicator")
        self.failureStatus_grid.addWidget(self.signalpickupStatus_indicator, 2, 1, 1, 1)
        self.gridLayout.addLayout(self.failureStatus_grid, 3, 3, 1, 1)
        self.block_grid = QtWidgets.QGridLayout()
        self.block_grid.setObjectName("block_grid")
        self.block_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.block_label.setFont(font)
        self.block_label.setTextFormat(QtCore.Qt.RichText)
        self.block_label.setScaledContents(False)
        self.block_label.setAlignment(QtCore.Qt.AlignCenter)
        self.block_label.setObjectName("block_label")
        self.block_grid.addWidget(self.block_label, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.block_grid, 8, 3, 1, 1)
        self.authority_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.authority_label.setFont(font)
        self.authority_label.setTextFormat(QtCore.Qt.RichText)
        self.authority_label.setScaledContents(False)
        self.authority_label.setAlignment(QtCore.Qt.AlignCenter)
        self.authority_label.setObjectName("authority_label")
        self.gridLayout.addWidget(self.authority_label, 4, 3, 1, 1)
        self.currentTime_text = QtWidgets.QTextBrowser(self.centralwidget)
        self.currentTime_text.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.currentTime_text.sizePolicy().hasHeightForWidth())
        self.currentTime_text.setSizePolicy(sizePolicy)
        self.currentTime_text.setMinimumSize(QtCore.QSize(1, 1))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(28)
        self.currentTime_text.setFont(font)
        self.currentTime_text.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.currentTime_text.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.currentTime_text.setObjectName("currentTime_text")
        self.gridLayout.addWidget(self.currentTime_text, 1, 0, 1, 1)
        self.doors_text = QtWidgets.QTextBrowser(self.centralwidget)
        self.doors_text.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.doors_text.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.doors_text.setObjectName("doors_text")
        self.gridLayout.addWidget(self.doors_text, 9, 4, 1, 1)
        self.lights_text = QtWidgets.QTextBrowser(self.centralwidget)
        self.lights_text.setObjectName("lights_text")
        self.gridLayout.addWidget(self.lights_text, 6, 4, 1, 1)
        self.trainNum_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.trainNum_label.setFont(font)
        self.trainNum_label.setAlignment(QtCore.Qt.AlignCenter)
        self.trainNum_label.setObjectName("trainNum_label")
        self.gridLayout.addWidget(self.trainNum_label, 2, 4, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout, 0, 0, 1, 1)
        TrainModel.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(TrainModel)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1920, 21))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menuDiagnostics_Page = QtWidgets.QMenu(self.menubar)
        self.menuDiagnostics_Page.setObjectName("menuDiagnostics_Page")
        #self.menuProperties_Page = QtWidgets.QMenu(self.menubar)
        #self.menuProperties_Page.setObjectName("menuProperties_Page")
        self.menuTesting_Page = QtWidgets.QMenu(self.menubar)
        self.menuTesting_Page.setObjectName("menuTesting_Page")
        TrainModel.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(TrainModel)
        self.statusbar.setObjectName("statusbar")
        TrainModel.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menuDiagnostics_Page.menuAction())
        #self.menubar.addAction(self.menuProperties_Page.menuAction())
        self.menubar.addAction(self.menuTesting_Page.menuAction())

        self.retranslateUi(TrainModel)
        QtCore.QMetaObject.connectSlotsByName(TrainModel)

        self.passengerPage_button.clicked.connect(self.passenger_button_pressed)
        self.diagnostics_button.clicked.connect(self.diagnostics_button_pressed)

        self.testingPage_button.clicked.connect(self.testing_button_pressed)

        


    def passenger_button_pressed(self):

        # self.passenger_page_window = QtWidgets.QDialog()
        # self.passenger_page_window.setModal(True)
        # self.passenger_page = Ui_TrainModel_Passenger(self)
        # self.passenger_page.setupUi(passenger_page_window)
        # self.passenger_page.show()

        # import sys
        # passenger_app = QtWidgets.QApplication(sys.argv)
        # TrainModelPassenger = QtWidgets.QMainWindow()
        # passenger_ui = Ui_TrainModel_Passenger()
        # passenger_ui.setupUi(TrainModelPassenger)
        # TrainModelPassenger.show()
        #sys.exit(passenger_app.exec_())

        link.train_model_ui_passenger_button_pressed.emit(self.currentTrainNum)

    def diagnostics_button_pressed(self):
        link.train_model_ui_diagnostics_button_pressed.emit(self.currentTrainNum)

    def testing_button_pressed(self):
        link.train_model_ui_testing_button_pressed.emit(self.currentTrainNum)

    def retranslateUi(self, TrainModel):
        _translate = QtCore.QCoreApplication.translate
        TrainModel.setWindowTitle(_translate("TrainModel", "MainWindow"))
        self.label.setText(_translate("TrainModel", "Lights"))
        self.currentTime_label.setText(_translate("TrainModel", "Current Time"))
        self.doors_label.setText(_translate("TrainModel", "Doors"))
        self.serviceBrakes_label.setText(_translate("TrainModel", "Service Brakes:"))
        self.emergencyBrakes_label.setText(_translate("TrainModel", "Emergency Brakes:"))
        self.emergencyBrakes_indicator.setText(_translate("TrainModel", "Disengaged"))
        self.serviceBrakes_indicator.setText(_translate("TrainModel", "Disengaged"))
        self.brakeStatus_label.setText(_translate("TrainModel", "Brake Status"))
        self.passengerPage_button.setText(_translate("TrainModel", "Passenger Page"))
        self.diagnostics_button.setText(_translate("TrainModel", "Diagnostics Page"))
        #self.propertiesPage_button.setText(_translate("TrainModel", "Properties Page"))
        self.testingPage_button.setText(_translate("TrainModel", "Testing Page"))
        self.departureTime_label.setText(_translate("TrainModel", "Departure Time"))
        self.currentSpeed_label.setText(_translate("TrainModel", "Current Speed"))
        self.suggestedSpeed_text.setHtml(_translate("TrainModel", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:28pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:16pt;\">80 mph</span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:16pt;\"><br /></p></body></html>"))
        self.commandedSpeed_label.setText(_translate("TrainModel", "Commanded Speed"))
        self.commandedSpeed_text.setHtml(_translate("TrainModel", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt;\">80 mph</span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:16pt;\"><br /></p></body></html>"))
        self.departureTime_text.setHtml(_translate("TrainModel", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:28pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:16pt;\">12:00:00</span></p></body></html>"))
        self.arrivalTime_label.setText(_translate("TrainModel", "Arrival Time"))
        self.arrivalTime_text.setHtml(_translate("TrainModel", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:28pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:16pt;\">12:00:00</span></p></body></html>"))
        self.temp_label.setText(_translate("TrainModel", "Temp"))
        self.suggestedSpeed_label.setText(_translate("TrainModel", "Suggested Speed"))
        self.authority_text.setHtml(_translate("TrainModel", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt;\">60 mi</span></p></body></html>"))
        self.power_text.setHtml(_translate("TrainModel", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:28pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:16pt;\">2000 kW</span></p></body></html>"))
        self.power_label.setText(_translate("TrainModel", "Power"))
        self.passengers_label.setText(_translate("TrainModel", "Passengers"))
        self.speedLimit_label.setText(_translate("TrainModel", "Speed Limit"))
        self.currentSpeed_text.setHtml(_translate("TrainModel", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:28pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:16pt;\">75 mph</span></p></body></html>"))
        self.nextStation_text.setHtml(_translate("TrainModel", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt;\">A</span></p></body></html>"))
        self.nextStation_label.setText(_translate("TrainModel", "Next Station"))
        self.failureStatus_label.setText(_translate("TrainModel", "Failure Status"))
        self.passengers_text.setHtml(_translate("TrainModel", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt;\">200</span></p></body></html>"))
        self.temp_text.setHtml(_translate("TrainModel", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt;\">72 F</span></p></body></html>"))
        self.block_text.setHtml(_translate("TrainModel", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:28pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:16pt;\">4A</span></p></body></html>"))
        self.speedLimit_text.setHtml(_translate("TrainModel", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:28pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:16pt;\">85 mph</span></p></body></html>"))
        self.brakeFailureStatus_label.setText(_translate("TrainModel", "Brake Status:"))
        self.signalPickupFailure_label.setText(_translate("TrainModel", "Signal Pickup Status:"))
        self.engineFailure_label.setText(_translate("TrainModel", "Engine Status:"))
        self.brakeStatus_indicator.setText(_translate("TrainModel", "Working"))
        self.engineStatus_indicator.setText(_translate("TrainModel", "Working"))
        self.signalpickupStatus_indicator.setText(_translate("TrainModel", "Working"))
        self.block_label.setText(_translate("TrainModel", "Block"))
        self.authority_label.setText(_translate("TrainModel", "Authority"))
        self.currentTime_text.setHtml(_translate("TrainModel", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:28pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:16pt;\">12:00:00</span></p></body></html>"))
        self.doors_text.setHtml(_translate("TrainModel", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt;\">Closed</span></p></body></html>"))
        self.trainNum_label.setText(_translate("TrainModel", "Train Number"))
        self.menu.setTitle(_translate("TrainModel", "Passenger Page"))
        self.menuDiagnostics_Page.setTitle(_translate("TrainModel", "Diagnostics Page"))
        #self.menuProperties_Page.setTitle(_translate("TrainModel", "Properties Page"))
        self.menuTesting_Page.setTitle(_translate("TrainModel", "Testing Page"))
        #self.trainNum_text.setText(_translate("TrainModel", str(self.currentTrainNum)))
        self.lights_text.setHtml(_translate("TrainModel", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt;\">Off</span></p></body></html>"))
        self.trainNum_text.setHtml(_translate("TrainModel", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt;\">0</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TrainModel = QtWidgets.QMainWindow()
    ui = Ui_TrainModel()
    ui.setupUi(TrainModel)
    TrainModel.show()
    sys.exit(app.exec_())

