from PyQt5 import QtCore, QtGui, QtWidgets


class Display(object):
    def setupUI(self, DisplayWindow):
        DisplayWindow.setObjectName("DisplayWindow")
        DisplayWindow.resize(1500, 1000)
        DisplayWindow.setAutoFillBackground(False)
        DisplayWindow.setStyleSheet("background-color: rgb(0, 102, 204);")
        
        self.centralwidget = QtWidgets.QWidget(DisplayWindow)
        self.centralwidget.setObjectName("centralwidget")
        
        self.displayLabel = QtWidgets.QLabel(self.centralwidget)
        self.displayLabel.setGeometry(QtCore.QRect(90, 80, 200, 31))
        self.displayLabel.setStyleSheet("font: 25pt \"MS Shell Dlg 2\";")
        self.displayLabel.setObjectName("displayLabel")
        
        self.speedLabel = QtWidgets.QLabel(self.centralwidget)
        self.speedLabel.setGeometry(QtCore.QRect(90, 120, 71, 31))
        self.speedLabel.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.speedLabel.setObjectName("speedLabel")
        
        self.destinationLabel = QtWidgets.QLabel(self.centralwidget)
        self.destinationLabel.setGeometry(QtCore.QRect(90, 160, 131, 31))
        self.destinationLabel.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.destinationLabel.setObjectName("destinationLabel")
        
        self.temperatureLabel = QtWidgets.QLabel(self.centralwidget)
        self.temperatureLabel.setGeometry(QtCore.QRect(90, 200, 141, 31))
        self.temperatureLabel.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.temperatureLabel.setObjectName("temperatureLabel")
        
        self.headlightsLabel = QtWidgets.QLabel(self.centralwidget)
        self.headlightsLabel.setGeometry(QtCore.QRect(90, 240, 121, 31))
        self.headlightsLabel.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.headlightsLabel.setObjectName("headlightsLabel")
        
        self.cabinlightLabel = QtWidgets.QLabel(self.centralwidget)
        self.cabinlightLabel.setGeometry(QtCore.QRect(90, 280, 131, 31))
        self.cabinlightLabel.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.cabinlightLabel.setObjectName("cabinlightLabel")
        
        self.doorstatusLabel = QtWidgets.QLabel(self.centralwidget)
        self.doorstatusLabel.setGeometry(QtCore.QRect(430, 120, 131, 31))
        self.doorstatusLabel.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.doorstatusLabel.setObjectName("doorstatusLabel")
        
        self.faultstatusLabel = QtWidgets.QLabel(self.centralwidget)
        self.faultstatusLabel.setGeometry(QtCore.QRect(430, 200, 131, 31))
        self.faultstatusLabel.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.faultstatusLabel.setObjectName("faultstatusLabel")
        
        self.nextstationOutput = QtWidgets.QLineEdit(self.centralwidget)
        self.nextstationOutput.setGeometry(QtCore.QRect(270, 160, 113, 31))
        self.nextstationOutput.setStyleSheet("background-color:rgb(224,232,245)")
        self.nextstationOutput.setText("")
        self.nextstationOutput.setReadOnly(True)
        self.nextstationOutput.setAlignment(QtCore.Qt.AlignCenter)
        self.nextstationOutput.setObjectName("nextstationOutput")
        
        self.faultStatusOutput = QtWidgets.QLineEdit(self.centralwidget)
        self.faultStatusOutput.setGeometry(QtCore.QRect(600, 200, 113, 31))
        self.faultStatusOutput.setStyleSheet("background-color:rgb(224,232,245)")
        self.faultStatusOutput.setText("")
        self.faultStatusOutput.setAlignment(QtCore.Qt.AlignCenter)
        self.faultStatusOutput.setReadOnly(True)
        self.faultStatusOutput.setObjectName("faultStatusOutput")
        
        self.modeOutput = QtWidgets.QLineEdit(self.centralwidget)
        self.modeOutput.setGeometry(QtCore.QRect(600, 240, 113, 31))
        self.modeOutput.setStyleSheet("background-color:rgb(224,232,245)")
        self.modeOutput.setText("")
        self.modeOutput.setAlignment(QtCore.Qt.AlignCenter)
        self.modeOutput.setObjectName("modeOutput")
        self.modeOutput.setReadOnly(True)
        
        self.modeLabel = QtWidgets.QLabel(self.centralwidget)
        self.modeLabel.setGeometry(QtCore.QRect(430, 240, 71, 31))
        self.modeLabel.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.modeLabel.setObjectName("modeLabel")

        self.powerLabel = QtWidgets.QLabel(self.centralwidget)
        self.powerLabel.setGeometry(QtCore.QRect(430, 80, 75, 31))
        self.powerLabel.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.powerLabel.setObjectName("powerLabel")

        self.powerOutput = QtWidgets.QLineEdit(self.centralwidget)
        self.powerOutput.setGeometry(QtCore.QRect(550, 80, 75, 31))
        self.powerOutput.setStyleSheet("background-color:rgb(224,232,245)")
        self.powerOutput.setText("")
        self.powerOutput.setAlignment(QtCore.Qt.AlignCenter)
        self.powerOutput.setObjectName("modeOutput")
        self.powerOutput.setReadOnly(True)
        
        self.speedInput = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.speedInput.setGeometry(QtCore.QRect(180, 120, 111, 31))
        self.speedInput.setTabletTracking(False)
        self.speedInput.setStyleSheet("background-color: rgb(224,232,245);")
        self.speedInput.setAlignment(QtCore.Qt.AlignCenter)
        self.speedInput.setObjectName("speedInput")
        
        self.actualSpeed = QtWidgets.QLineEdit(self.centralwidget)
        self.actualSpeed.setGeometry(QtCore.QRect(300, 120, 113, 31))
        self.actualSpeed.setStyleSheet("background-color:rgb(224,232,245)")
        self.actualSpeed.setText("")
        self.actualSpeed.setAlignment(QtCore.Qt.AlignCenter)
        self.actualSpeed.setObjectName("actualSpeed")
        self.actualSpeed.setReadOnly(True)
        self.actualSpeed.setMaxLength(5)
        
        self.temperatureInput = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.temperatureInput.setGeometry(QtCore.QRect(270, 200, 111, 31))
        self.temperatureInput.setTabletTracking(False)
        self.temperatureInput.setStyleSheet("background-color: rgb(224,232,245);")
        self.temperatureInput.setAlignment(QtCore.Qt.AlignCenter)
        self.temperatureInput.setObjectName("temperatureInput")
        
        self.headlightOnButton = QtWidgets.QPushButton(self.centralwidget)
        self.headlightOnButton.setGeometry(QtCore.QRect(270, 240, 51, 31))
        self.headlightOnButton.setStyleSheet("background-color:rgb(224,232,245)")
        self.headlightOnButton.setObjectName("headlightOnButton")
        
        self.headlightOffButton = QtWidgets.QPushButton(self.centralwidget)
        self.headlightOffButton.setGeometry(QtCore.QRect(330, 240, 51, 31))
        self.headlightOffButton.setStyleSheet("background-color:rgb(224,232,245)")
        self.headlightOffButton.setObjectName("headlightOffButton")
        
        self.cabinlightOnButton = QtWidgets.QPushButton(self.centralwidget)
        self.cabinlightOnButton.setGeometry(QtCore.QRect(270, 280, 51, 31))
        self.cabinlightOnButton.setStyleSheet("background-color:rgb(224,232,245)")
        self.cabinlightOnButton.setObjectName("cabinlightOnButton")

        self.cabinlightOffButton = QtWidgets.QPushButton(self.centralwidget)
        self.cabinlightOffButton.setGeometry(QtCore.QRect(330, 280, 51, 31))
        self.cabinlightOffButton.setStyleSheet("background-color:rgb(224,232,245)")
        self.cabinlightOffButton.setObjectName("cabinlightOffButton")
        
        self.doorOpenButton = QtWidgets.QPushButton(self.centralwidget)
        self.doorOpenButton.setGeometry(QtCore.QRect(600, 120, 51, 31))
        self.doorOpenButton.setStyleSheet("background-color:rgb(224,232,245)")
        self.doorOpenButton.setObjectName("doorOpenButton")
        
        self.doorCloseButton = QtWidgets.QPushButton(self.centralwidget)
        self.doorCloseButton.setGeometry(QtCore.QRect(660, 120, 51, 31))
        self.doorCloseButton.setStyleSheet("background-color:rgb(224,232,245)")
        self.doorCloseButton.setObjectName("doorCloseButton")
        
        self.kpLabel = QtWidgets.QLabel(self.centralwidget)
        self.kpLabel.setGeometry(QtCore.QRect(430, 160, 41, 31))
        self.kpLabel.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.kpLabel.setObjectName("kpLabel")
        
        self.kpInput = QtWidgets.QLineEdit(self.centralwidget)
        self.kpInput.setGeometry(QtCore.QRect(480, 160, 81, 31))
        self.kpInput.setStyleSheet("background-color:rgb(224,232,245)")
        self.kpInput.setReadOnly(True)
        self.kpInput.setAlignment(QtCore.Qt.AlignCenter)
        self.kpInput.setObjectName("kpInput")
        
        self.kiLabel = QtWidgets.QLabel(self.centralwidget)
        self.kiLabel.setGeometry(QtCore.QRect(600, 160, 41, 31))
        self.kiLabel.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.kiLabel.setObjectName("kiLabel")
        
        self.kiInput = QtWidgets.QLineEdit(self.centralwidget)
        self.kiInput.setGeometry(QtCore.QRect(650, 160, 81, 31))
        self.kiInput.setStyleSheet("background-color: rgb(224,232,245);")
        self.kiInput.setReadOnly(True)
        self.kiInput.setAlignment(QtCore.Qt.AlignCenter)
        self.kiInput.setObjectName("kiInput")
        
        self.servicebrakeButton = QtWidgets.QPushButton(self.centralwidget)
        self.servicebrakeButton.setGeometry(QtCore.QRect(90, 330, 111, 81))
        self.servicebrakeButton.setStyleSheet("background-color:rgb(224,232,245)")
        self.servicebrakeButton.setObjectName("servicebrakeButton")
        
        self.emergencybrakeButton = QtWidgets.QPushButton(self.centralwidget)
        self.emergencybrakeButton.setGeometry(QtCore.QRect(270, 330, 111, 81))
        self.emergencybrakeButton.setStyleSheet("background-color: rgb(255, 23, 2);")
        self.emergencybrakeButton.setObjectName("emergencybrakeButton")
        
        self.announcementButton = QtWidgets.QPushButton(self.centralwidget)
        self.announcementButton.setGeometry(QtCore.QRect(430, 330, 111, 81))
        self.announcementButton.setStyleSheet("background-color:rgb(224,232,245)")
        self.announcementButton.setObjectName("announcementButton")
        
        self.automaticModeButton = QtWidgets.QPushButton(self.centralwidget)
        self.automaticModeButton.setGeometry(QtCore.QRect(600, 330, 111, 81))
        self.automaticModeButton.setStyleSheet("background-color: rgb(224,232,245);")
        self.automaticModeButton.setObjectName("automaticModeButton")
        
        self.enginestatusLabel = QtWidgets.QLabel(self.centralwidget)
        self.enginestatusLabel.setGeometry(QtCore.QRect(430, 280, 151, 31))
        self.enginestatusLabel.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.enginestatusLabel.setObjectName("enginestatusLabel")
        
        self.engineOnButton = QtWidgets.QPushButton(self.centralwidget)
        self.engineOnButton.setGeometry(QtCore.QRect(600, 280, 51, 31))
        self.engineOnButton.setStyleSheet("background-color:rgb(224,232,245)")
        self.engineOnButton.setObjectName("engineOnButton")
        
        self.engineOffButton = QtWidgets.QPushButton(self.centralwidget)
        self.engineOffButton.setGeometry(QtCore.QRect(660, 280, 51, 31))
        self.engineOffButton.setStyleSheet("background-color:rgb(224,232,245)")
        self.engineOffButton.setObjectName("engineOffButton")
        
        DisplayWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(DisplayWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 768, 26))
        self.menubar.setObjectName("menubar")       

        self.retranslateUi(DisplayWindow)
        QtCore.QMetaObject.connectSlotsByName(DisplayWindow)

    def retranslateUi(self, DisplayWindow):
        _translate = QtCore.QCoreApplication.translate
        DisplayWindow.setWindowTitle(_translate("DisplayWindow", "MainWindow"))
        self.displayLabel.setText(_translate("DisplayWindow", "Train Control"))
        self.speedLabel.setText(_translate("DisplayWindow", "Speed:"))
        self.destinationLabel.setText(_translate("DisplayWindow", "Next Station:"))
        self.temperatureLabel.setText(_translate("DisplayWindow", "Temperature:"))
        self.headlightsLabel.setText(_translate("DisplayWindow", "Headlights: "))
        self.cabinlightLabel.setText(_translate("DisplayWindow", "Cabin Lights:"))
        self.doorstatusLabel.setText(_translate("DisplayWindow", "Door Status:"))
        self.faultstatusLabel.setText(_translate("DisplayWindow", "Fault Status:"))
        self.powerLabel.setText(_translate("DisplayWindow", "Power:"))
        self.modeLabel.setText(_translate("DisplayWindow", "Mode:"))
        self.headlightOnButton.setText(_translate("DisplayWindow", "ON"))
        self.headlightOffButton.setText(_translate("DisplayWindow", "OFF"))
        self.cabinlightOnButton.setText(_translate("DisplayWindow", "ON"))
        self.doorOpenButton.setText(_translate("DisplayWindow", "OPEN"))
        self.cabinlightOffButton.setText(_translate("DisplayWindow", "OFF"))
        self.doorCloseButton.setText(_translate("DisplayWindow", "CLOSE"))
        self.kpLabel.setText(_translate("DisplayWindow", "Kp:"))
        self.kiLabel.setText(_translate("DisplayWindow", "Ki:"))
        self.servicebrakeButton.setText(_translate("DisplayWindow", "SERVICE\nBRAKE"))
        self.emergencybrakeButton.setText(_translate("DisplayWindow", "EMERGENCY\nBRAKE"))
        self.announcementButton.setText(_translate("DisplayWindow", "MAKE\nANNOUNCEMENT"))
        self.automaticModeButton.setText(_translate("DisplayWindow", "SWITCH TO\nAUTOMATIC\nMODE"))
        self.enginestatusLabel.setText(_translate("DisplayWindow", "Engine Status:"))
        self.engineOnButton.setText(_translate("DisplayWindow", "ON"))
        self.engineOffButton.setText(_translate("DisplayWindow", "OFF"))
